name: C/C++ Release candidate macos

on:
  release:
    types: [published]
  push:
    branches:
       - macos-image-build-test
#      - rc
#      - debug_macos

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: check autoconf version
      run: autoconf --version
    - name: update automake for mpfr
      run: |
        curl -O -L http://ftpmirror.gnu.org/automake/automake-1.16.5.tar.gz
        tar -xzf automake-1.16.5.tar.gz
        cd automake-*
        ./configure
        make
        sudo make install
        automake --version
    - name: build deps & slicer
      run: ./BuildMacOS.sh -dsi
#    - name: Upload artifact
#      uses: actions/upload-artifact@v4.0.0
#      with:
#        name: DFL_macos.app
#        path: build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: DFL_macos.dmg
        path: SuperSlicer.dmg
